<?php
/**
 * Twenty Twenty-Two: Block Patterns
 *
 * @since Twenty Twenty-Two 1.0
 */
return array(
	'footer-blog',
	'footer-dark',
	'footer-default',
	'footer-logo',
	'footer-navigation-copyright',
	'footer-navigation',
	'footer-query-images-title-citation',
	'footer-query-title-citation',
	'footer-social-copyright',
	// 'footer-title-tagline-social',
	// 'footer-about-title-logo',
	// 'general-subscribe',
	// 'general-featured-posts',
	// 'general-layered-images-with-duotone',
	// 'general-wide-image-intro-buttons',
	// 'general-large-list-names',
	// 'general-video-header-details',
	// 'general-list-events',
	// 'general-two-images-text',
	// 'general-image-with-caption',
	// 'general-video-trailer',
	// 'general-pricing-table',
	// 'general-divider-light',
	// 'general-divider-dark',
	// 'header-default',
	// 'header-large-dark',
	// 'header-small-dark',
	// 'header-image-background',
	// 'header-image-background-overlay',
	// 'header-with-tagline',
	// 'header-text-only-green-background',
	// 'header-text-only-salmon-background',
	// 'header-title-and-button',
	// 'header-text-only-with-tagline-black-background',
	// 'header-logo-navigation-gray-background',
	// 'header-logo-navigation-social-black-background',
	// 'header-title-navigation-social',
	// 'header-logo-navigation-offset-tagline',
	// 'header-stacked',
	// 'header-centered-logo',
	// 'header-centered-logo-black-background',
	// 'header-centered-title-navigation-social',
	// 'header-title-and-button',
	'hidden-404',
	// 'hidden-bird',
	// 'hidden-heading-and-bird',
	// 'page-about-media-left',
	// 'page-about-simple-dark',
	// 'page-about-media-right',
	// 'page-about-solid-color',
	// 'page-about-links',
	// 'page-about-links-dark',
	// 'page-about-large-image-and-buttons',
	// 'page-layout-image-and-text',
	// 'page-layout-image-text-and-video',
	// 'page-layout-two-columns',
	// 'page-sidebar-poster',
	// 'page-sidebar-grid-posts',
	// 'page-sidebar-blog-posts',
	// 'page-sidebar-blog-posts-right',
	// 'query-default',
	// 'query-simple-blog',
	// 'query-grid',
	// 'query-text-grid',
	// 'query-image-grid',
	// 'query-large-titles',
	// 'query-irregular-grid',
);
